[2024-10-23T08:49:13.134+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T08:49:13.152+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [queued]>
[2024-10-23T08:49:13.164+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [queued]>
[2024-10-23T08:49:13.165+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-23T08:49:13.192+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-23 08:41:37.869558+00:00
[2024-10-23T08:49:13.199+0000] {standard_task_runner.py:72} INFO - Started process 23934 to run task
[2024-10-23T08:49:13.205+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'run_selenium_task', 'manual__2024-10-23T08:41:37.869558+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpbchsjyjl']
[2024-10-23T08:49:13.208+0000] {standard_task_runner.py:105} INFO - Job 856: Subtask run_selenium_task
[2024-10-23T08:49:13.277+0000] {task_command.py:467} INFO - Running <TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [running]> on host 60bbe790d101
[2024-10-23T08:49:13.427+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T08:41:37.869558+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T08:41:37.869558+00:00'
[2024-10-23T08:49:13.428+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T08:49:13.473+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-23T08:49:14.345+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:49:14.530+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:49:14.686+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver-linux64/chromedriver] found in cache
[2024-10-23T08:50:36.684+0000] {job.py:229} INFO - Heartbeat recovered after 15.15 seconds
[2024-10-23T08:50:57.407+0000] {job.py:229} INFO - Heartbeat recovered after 23.89 seconds
[2024-10-23T08:52:36.838+0000] {job.py:229} INFO - Heartbeat recovered after 106.68 seconds
[2024-10-23T08:53:21.078+0000] {job.py:229} INFO - Heartbeat recovered after 18.92 seconds
[2024-10-23T08:53:37.253+0000] {job.py:229} INFO - Heartbeat recovered after 20.37 seconds
[2024-10-23T08:53:52.227+0000] {job.py:229} INFO - Heartbeat recovered after 16.98 seconds
[2024-10-23T08:54:30.019+0000] {job.py:229} INFO - Heartbeat recovered after 40.39 seconds
[2024-10-23T08:55:47.758+0000] {job.py:229} INFO - Heartbeat recovered after 93.67 seconds
[2024-10-23T08:56:54.051+0000] {job.py:229} INFO - Heartbeat recovered after 10.96 seconds
[2024-10-23T08:57:05.913+0000] {job.py:229} INFO - Heartbeat recovered after 13.68 seconds
[2024-10-23T08:57:17.593+0000] {job.py:229} INFO - Heartbeat recovered after 12.79 seconds
[2024-10-23T08:57:37.412+0000] {job.py:229} INFO - Heartbeat recovered after 11.50 seconds
[2024-10-23T08:57:48.162+0000] {job.py:229} INFO - Heartbeat recovered after 12.83 seconds
[2024-10-23T08:58:06.553+0000] {job.py:229} INFO - Heartbeat recovered after 20.13 seconds
[2024-10-23T08:58:20.073+0000] {job.py:229} INFO - Heartbeat recovered after 15.19 seconds
[2024-10-23T08:58:38.052+0000] {job.py:229} INFO - Heartbeat recovered after 18.71 seconds
[2024-10-23T08:58:56.220+0000] {job.py:229} INFO - Heartbeat recovered after 19.15 seconds
[2024-10-23T08:59:10.075+0000] {job.py:229} INFO - Heartbeat recovered after 14.60 seconds
[2024-10-23T08:59:31.393+0000] {job.py:229} INFO - Heartbeat recovered after 23.16 seconds
[2024-10-23T09:00:07.260+0000] {job.py:229} INFO - Heartbeat recovered after 39.98 seconds
[2024-10-23T09:01:13.970+0000] {job.py:229} INFO - Heartbeat recovered after 72.04 seconds
[2024-10-23T09:01:15.631+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 274, in selenium_scraper
    driver.get("https://www.google.com")
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5579b1dbf10a <unknown>
#1 0x5579b18da460 <unknown>
#2 0x5579b18c2b00 <unknown>
#3 0x5579b18c27ed <unknown>
#4 0x5579b18c087c <unknown>
#5 0x5579b18c102f <unknown>
#6 0x5579b18d0497 <unknown>
#7 0x5579b18e6474 <unknown>
#8 0x5579b18eb7ab <unknown>
#9 0x5579b18c173e <unknown>
#10 0x5579b18e62d8 <unknown>
#11 0x5579b19699bf <unknown>
#12 0x5579b194adb3 <unknown>
#13 0x5579b1919c10 <unknown>
#14 0x5579b191abee <unknown>
#15 0x5579b1d8b39b <unknown>
#16 0x5579b1d8f338 <unknown>
#17 0x5579b1d78ebc <unknown>
#18 0x5579b1d8feb7 <unknown>
#19 0x5579b1d5e10f <unknown>
#20 0x5579b1dad828 <unknown>
#21 0x5579b1dad9f0 <unknown>
#22 0x5579b1dbdf86 <unknown>
#23 0x7f89aef17144 <unknown>

[2024-10-23T09:01:15.659+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test, task_id=run_selenium_task, run_id=manual__2024-10-23T08:41:37.869558+00:00, execution_date=20241023T084137, start_date=20241023T084913, end_date=20241023T090115
[2024-10-23T09:01:15.701+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T09:01:15.702+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 856 for task run_selenium_task (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5579b1dbf10a <unknown>
#1 0x5579b18da460 <unknown>
#2 0x5579b18c2b00 <unknown>
#3 0x5579b18c27ed <unknown>
#4 0x5579b18c087c <unknown>
#5 0x5579b18c102f <unknown>
#6 0x5579b18d0497 <unknown>
#7 0x5579b18e6474 <unknown>
#8 0x5579b18eb7ab <unknown>
#9 0x5579b18c173e <unknown>
#10 0x5579b18e62d8 <unknown>
#11 0x5579b19699bf <unknown>
#12 0x5579b194adb3 <unknown>
#13 0x5579b1919c10 <unknown>
#14 0x5579b191abee <unknown>
#15 0x5579b1d8b39b <unknown>
#16 0x5579b1d8f338 <unknown>
#17 0x5579b1d78ebc <unknown>
#18 0x5579b1d8feb7 <unknown>
#19 0x5579b1d5e10f <unknown>
#20 0x5579b1dad828 <unknown>
#21 0x5579b1dad9f0 <unknown>
#22 0x5579b1dbdf86 <unknown>
#23 0x7f89aef17144 <unknown>
; 23934)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 274, in selenium_scraper
    driver.get("https://www.google.com")
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5579b1dbf10a <unknown>
#1 0x5579b18da460 <unknown>
#2 0x5579b18c2b00 <unknown>
#3 0x5579b18c27ed <unknown>
#4 0x5579b18c087c <unknown>
#5 0x5579b18c102f <unknown>
#6 0x5579b18d0497 <unknown>
#7 0x5579b18e6474 <unknown>
#8 0x5579b18eb7ab <unknown>
#9 0x5579b18c173e <unknown>
#10 0x5579b18e62d8 <unknown>
#11 0x5579b19699bf <unknown>
#12 0x5579b194adb3 <unknown>
#13 0x5579b1919c10 <unknown>
#14 0x5579b191abee <unknown>
#15 0x5579b1d8b39b <unknown>
#16 0x5579b1d8f338 <unknown>
#17 0x5579b1d78ebc <unknown>
#18 0x5579b1d8feb7 <unknown>
#19 0x5579b1d5e10f <unknown>
#20 0x5579b1dad828 <unknown>
#21 0x5579b1dad9f0 <unknown>
#22 0x5579b1dbdf86 <unknown>
#23 0x7f89aef17144 <unknown>

[2024-10-23T09:01:15.748+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T09:01:15.762+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T09:01:15.763+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
