[2024-10-23T08:41:47.576+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T08:41:47.594+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [queued]>
[2024-10-23T08:41:47.606+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [queued]>
[2024-10-23T08:41:47.606+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T08:41:47.638+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-23 08:41:37.869558+00:00
[2024-10-23T08:41:47.645+0000] {standard_task_runner.py:72} INFO - Started process 23802 to run task
[2024-10-23T08:41:47.651+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'run_selenium_task', 'manual__2024-10-23T08:41:37.869558+00:00', '--job-id', '855', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpgm78sxqh']
[2024-10-23T08:41:47.654+0000] {standard_task_runner.py:105} INFO - Job 855: Subtask run_selenium_task
[2024-10-23T08:41:47.774+0000] {task_command.py:467} INFO - Running <TaskInstance: test.run_selenium_task manual__2024-10-23T08:41:37.869558+00:00 [running]> on host 60bbe790d101
[2024-10-23T08:41:47.891+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T08:41:37.869558+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T08:41:37.869558+00:00'
[2024-10-23T08:41:47.892+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T08:41:47.938+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-23T08:41:49.363+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:41:49.565+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:41:49.718+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver-linux64/chromedriver] found in cache
[2024-10-23T08:42:05.529+0000] {job.py:229} INFO - Heartbeat recovered after 12.26 seconds
[2024-10-23T08:42:21.580+0000] {job.py:229} INFO - Heartbeat recovered after 18.79 seconds
[2024-10-23T08:43:02.774+0000] {job.py:229} INFO - Heartbeat recovered after 42.05 seconds
[2024-10-23T08:44:04.326+0000] {job.py:229} INFO - Heartbeat recovered after 46.77 seconds
[2024-10-23T08:44:04.690+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 271, in selenium_scraper
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x5608ed47110a <unknown>
#1 0x5608ecf8c460 <unknown>
#2 0x5608ecfc7044 <unknown>
#3 0x5608ecfc27ae <unknown>
#4 0x5608ecfbdca5 <unknown>
#5 0x5608ed009156 <unknown>
#6 0x5608ed0087a6 <unknown>
#7 0x5608ecffcdb3 <unknown>
#8 0x5608ecfcbc10 <unknown>
#9 0x5608ecfccbee <unknown>
#10 0x5608ed43d39b <unknown>
#11 0x5608ed441338 <unknown>
#12 0x5608ed42aebc <unknown>
#13 0x5608ed441eb7 <unknown>
#14 0x5608ed41010f <unknown>
#15 0x5608ed45f828 <unknown>
#16 0x5608ed45f9f0 <unknown>
#17 0x5608ed46ff86 <unknown>
#18 0x7f2ad4872144 <unknown>

[2024-10-23T08:44:04.879+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=run_selenium_task, run_id=manual__2024-10-23T08:41:37.869558+00:00, execution_date=20241023T084137, start_date=20241023T084147, end_date=20241023T084404
[2024-10-23T08:44:05.347+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T08:44:05.389+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 855 for task run_selenium_task (Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x5608ed47110a <unknown>
#1 0x5608ecf8c460 <unknown>
#2 0x5608ecfc7044 <unknown>
#3 0x5608ecfc27ae <unknown>
#4 0x5608ecfbdca5 <unknown>
#5 0x5608ed009156 <unknown>
#6 0x5608ed0087a6 <unknown>
#7 0x5608ecffcdb3 <unknown>
#8 0x5608ecfcbc10 <unknown>
#9 0x5608ecfccbee <unknown>
#10 0x5608ed43d39b <unknown>
#11 0x5608ed441338 <unknown>
#12 0x5608ed42aebc <unknown>
#13 0x5608ed441eb7 <unknown>
#14 0x5608ed41010f <unknown>
#15 0x5608ed45f828 <unknown>
#16 0x5608ed45f9f0 <unknown>
#17 0x5608ed46ff86 <unknown>
#18 0x7f2ad4872144 <unknown>
; 23802)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 271, in selenium_scraper
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
#0 0x5608ed47110a <unknown>
#1 0x5608ecf8c460 <unknown>
#2 0x5608ecfc7044 <unknown>
#3 0x5608ecfc27ae <unknown>
#4 0x5608ecfbdca5 <unknown>
#5 0x5608ed009156 <unknown>
#6 0x5608ed0087a6 <unknown>
#7 0x5608ecffcdb3 <unknown>
#8 0x5608ecfcbc10 <unknown>
#9 0x5608ecfccbee <unknown>
#10 0x5608ed43d39b <unknown>
#11 0x5608ed441338 <unknown>
#12 0x5608ed42aebc <unknown>
#13 0x5608ed441eb7 <unknown>
#14 0x5608ed41010f <unknown>
#15 0x5608ed45f828 <unknown>
#16 0x5608ed45f9f0 <unknown>
#17 0x5608ed46ff86 <unknown>
#18 0x7f2ad4872144 <unknown>

[2024-10-23T08:44:05.697+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T08:44:05.831+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T08:44:05.832+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
