[2024-10-22T11:53:17.899+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-22T11:53:17.914+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: selenium_scraper_dag_with_slack.run_selenium_task manual__2024-10-22T11:52:08.283136+00:00 [queued]>
[2024-10-22T11:53:17.923+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: selenium_scraper_dag_with_slack.run_selenium_task manual__2024-10-22T11:52:08.283136+00:00 [queued]>
[2024-10-22T11:53:17.923+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-10-22T11:53:17.942+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-22 11:52:08.283136+00:00
[2024-10-22T11:53:17.949+0000] {standard_task_runner.py:72} INFO - Started process 9242 to run task
[2024-10-22T11:53:17.955+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'selenium_scraper_dag_with_slack', 'run_selenium_task', 'manual__2024-10-22T11:52:08.283136+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/slacktest.py', '--cfg-path', '/tmp/tmpxrwmniqi']
[2024-10-22T11:53:17.958+0000] {standard_task_runner.py:105} INFO - Job 473: Subtask run_selenium_task
[2024-10-22T11:53:18.013+0000] {task_command.py:467} INFO - Running <TaskInstance: selenium_scraper_dag_with_slack.run_selenium_task manual__2024-10-22T11:52:08.283136+00:00 [running]> on host 60bbe790d101
[2024-10-22T11:53:18.103+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='selenium_scraper_dag_with_slack' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T11:52:08.283136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T11:52:08.283136+00:00'
[2024-10-22T11:53:18.104+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-22T11:53:18.124+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-22T11:53:18.817+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-22T11:53:18.962+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-22T11:53:19.085+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.58/chromedriver-linux64/chromedriver] found in cache
[2024-10-22T11:53:27.960+0000] {logging_mixin.py:190} INFO - Page title is: Google
[2024-10-22T11:55:25.990+0000] {job.py:229} INFO - Heartbeat recovered after 12.31 seconds
[2024-10-22T11:55:40.111+0000] {job.py:229} INFO - Heartbeat recovered after 18.09 seconds
[2024-10-22T11:55:58.849+0000] {job.py:229} INFO - Heartbeat recovered after 19.43 seconds
[2024-10-22T11:56:21.843+0000] {job.py:229} INFO - Heartbeat recovered after 25.91 seconds
[2024-10-22T11:56:43.066+0000] {job.py:229} INFO - Heartbeat recovered after 24.51 seconds
[2024-10-22T11:57:12.580+0000] {job.py:229} INFO - Heartbeat recovered after 31.42 seconds
[2024-10-22T11:57:49.614+0000] {job.py:229} INFO - Heartbeat recovered after 41.80 seconds
[2024-10-22T11:58:10.369+0000] {job.py:229} INFO - Heartbeat recovered after 25.04 seconds
[2024-10-22T11:58:30.776+0000] {job.py:229} INFO - Heartbeat recovered after 24.45 seconds
[2024-10-22T11:58:58.251+0000] {job.py:229} INFO - Heartbeat recovered after 29.79 seconds
[2024-10-22T11:59:00.478+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/slacktest.py", line 46, in selenium_scraper
    print("New page title is:", driver.title)
                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 374, in title
    return self.execute(Command.GET_TITLE).get("value", "")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x564d0d81a0aa <unknown>
#1 0x564d0d3311a0 <unknown>
#2 0x564d0d319840 <unknown>
#3 0x564d0d31952d <unknown>
#4 0x564d0d3175bc <unknown>
#5 0x564d0d317d6f <unknown>
#6 0x564d0d3271d7 <unknown>
#7 0x564d0d33d1e4 <unknown>
#8 0x564d0d34251b <unknown>
#9 0x564d0d31847e <unknown>
#10 0x564d0d33cfee <unknown>
#11 0x564d0d3c0acb <unknown>
#12 0x564d0d3a1b23 <unknown>
#13 0x564d0d370990 <unknown>
#14 0x564d0d37196e <unknown>
#15 0x564d0d7e616b <unknown>
#16 0x564d0d7e9f68 <unknown>
#17 0x564d0d7d364c <unknown>
#18 0x564d0d7eaae7 <unknown>
#19 0x564d0d7b84af <unknown>
#20 0x564d0d8084f8 <unknown>
#21 0x564d0d8086c0 <unknown>
#22 0x564d0d818f26 <unknown>
#23 0x7fbd307b7144 <unknown>

[2024-10-22T11:59:00.523+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=selenium_scraper_dag_with_slack, task_id=run_selenium_task, run_id=manual__2024-10-22T11:52:08.283136+00:00, execution_date=20241022T115208, start_date=20241022T115317, end_date=20241022T115900
[2024-10-22T11:59:00.572+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-22T11:59:00.573+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 473 for task run_selenium_task (Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x564d0d81a0aa <unknown>
#1 0x564d0d3311a0 <unknown>
#2 0x564d0d319840 <unknown>
#3 0x564d0d31952d <unknown>
#4 0x564d0d3175bc <unknown>
#5 0x564d0d317d6f <unknown>
#6 0x564d0d3271d7 <unknown>
#7 0x564d0d33d1e4 <unknown>
#8 0x564d0d34251b <unknown>
#9 0x564d0d31847e <unknown>
#10 0x564d0d33cfee <unknown>
#11 0x564d0d3c0acb <unknown>
#12 0x564d0d3a1b23 <unknown>
#13 0x564d0d370990 <unknown>
#14 0x564d0d37196e <unknown>
#15 0x564d0d7e616b <unknown>
#16 0x564d0d7e9f68 <unknown>
#17 0x564d0d7d364c <unknown>
#18 0x564d0d7eaae7 <unknown>
#19 0x564d0d7b84af <unknown>
#20 0x564d0d8084f8 <unknown>
#21 0x564d0d8086c0 <unknown>
#22 0x564d0d818f26 <unknown>
#23 0x7fbd307b7144 <unknown>
; 9242)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/slacktest.py", line 46, in selenium_scraper
    print("New page title is:", driver.title)
                                ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 374, in title
    return self.execute(Command.GET_TITLE).get("value", "")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x564d0d81a0aa <unknown>
#1 0x564d0d3311a0 <unknown>
#2 0x564d0d319840 <unknown>
#3 0x564d0d31952d <unknown>
#4 0x564d0d3175bc <unknown>
#5 0x564d0d317d6f <unknown>
#6 0x564d0d3271d7 <unknown>
#7 0x564d0d33d1e4 <unknown>
#8 0x564d0d34251b <unknown>
#9 0x564d0d31847e <unknown>
#10 0x564d0d33cfee <unknown>
#11 0x564d0d3c0acb <unknown>
#12 0x564d0d3a1b23 <unknown>
#13 0x564d0d370990 <unknown>
#14 0x564d0d37196e <unknown>
#15 0x564d0d7e616b <unknown>
#16 0x564d0d7e9f68 <unknown>
#17 0x564d0d7d364c <unknown>
#18 0x564d0d7eaae7 <unknown>
#19 0x564d0d7b84af <unknown>
#20 0x564d0d8084f8 <unknown>
#21 0x564d0d8086c0 <unknown>
#22 0x564d0d818f26 <unknown>
#23 0x7fbd307b7144 <unknown>

[2024-10-22T11:59:00.618+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-22T11:59:00.674+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T11:59:00.675+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
