[2024-10-23T08:27:50.125+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T08:27:50.144+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:25:24.179394+00:00 [queued]>
[2024-10-23T08:27:50.157+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T08:25:24.179394+00:00 [queued]>
[2024-10-23T08:27:50.158+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T08:27:50.219+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-23 08:25:24.179394+00:00
[2024-10-23T08:27:50.227+0000] {standard_task_runner.py:72} INFO - Started process 23483 to run task
[2024-10-23T08:27:50.256+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'run_selenium_task', 'manual__2024-10-23T08:25:24.179394+00:00', '--job-id', '855', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpkfwtenil']
[2024-10-23T08:27:50.263+0000] {standard_task_runner.py:105} INFO - Job 855: Subtask run_selenium_task
[2024-10-23T08:27:50.440+0000] {task_command.py:467} INFO - Running <TaskInstance: test.run_selenium_task manual__2024-10-23T08:25:24.179394+00:00 [running]> on host 60bbe790d101
[2024-10-23T08:27:50.741+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T08:25:24.179394+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T08:25:24.179394+00:00'
[2024-10-23T08:27:50.743+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T08:27:50.795+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-23T08:27:51.475+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:27:51.641+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T08:27:51.783+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver-linux64/chromedriver] found in cache
[2024-10-23T08:30:34.271+0000] {job.py:229} INFO - Heartbeat recovered after 47.28 seconds
[2024-10-23T08:30:44.525+0000] {job.py:229} INFO - Heartbeat recovered after 12.79 seconds
[2024-10-23T08:30:54.435+0000] {job.py:229} INFO - Heartbeat recovered after 10.98 seconds
[2024-10-23T08:31:28.533+0000] {job.py:229} INFO - Heartbeat recovered after 35.00 seconds
[2024-10-23T08:32:03.709+0000] {job.py:229} INFO - Heartbeat recovered after 48.25 seconds
[2024-10-23T08:33:00.524+0000] {job.py:229} INFO - Heartbeat recovered after 11.72 seconds
[2024-10-23T08:36:00.439+0000] {job.py:229} INFO - Heartbeat recovered after 155.67 seconds
[2024-10-23T08:36:02.223+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 274, in selenium_scraper
    driver.get("https://www.google.com")
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.353
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5611ad1c810a <unknown>
#1 0x5611acce3460 <unknown>
#2 0x5611acccbb00 <unknown>
#3 0x5611acccb7ed <unknown>
#4 0x5611accc987c <unknown>
#5 0x5611accca02f <unknown>
#6 0x5611accd9497 <unknown>
#7 0x5611accef474 <unknown>
#8 0x5611accf47ab <unknown>
#9 0x5611accca73e <unknown>
#10 0x5611accef2d8 <unknown>
#11 0x5611acd72d5b <unknown>
#12 0x5611acd53db3 <unknown>
#13 0x5611acd22c10 <unknown>
#14 0x5611acd23bee <unknown>
#15 0x5611ad19439b <unknown>
#16 0x5611ad198338 <unknown>
#17 0x5611ad181ebc <unknown>
#18 0x5611ad198eb7 <unknown>
#19 0x5611ad16710f <unknown>
#20 0x5611ad1b6828 <unknown>
#21 0x5611ad1b69f0 <unknown>
#22 0x5611ad1c6f86 <unknown>
#23 0x7f63cf90e144 <unknown>

[2024-10-23T08:36:02.271+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=run_selenium_task, run_id=manual__2024-10-23T08:25:24.179394+00:00, execution_date=20241023T082524, start_date=20241023T082750, end_date=20241023T083602
[2024-10-23T08:36:02.326+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T08:36:02.327+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 855 for task run_selenium_task (Message: timeout: Timed out receiving message from renderer: 299.353
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5611ad1c810a <unknown>
#1 0x5611acce3460 <unknown>
#2 0x5611acccbb00 <unknown>
#3 0x5611acccb7ed <unknown>
#4 0x5611accc987c <unknown>
#5 0x5611accca02f <unknown>
#6 0x5611accd9497 <unknown>
#7 0x5611accef474 <unknown>
#8 0x5611accf47ab <unknown>
#9 0x5611accca73e <unknown>
#10 0x5611accef2d8 <unknown>
#11 0x5611acd72d5b <unknown>
#12 0x5611acd53db3 <unknown>
#13 0x5611acd22c10 <unknown>
#14 0x5611acd23bee <unknown>
#15 0x5611ad19439b <unknown>
#16 0x5611ad198338 <unknown>
#17 0x5611ad181ebc <unknown>
#18 0x5611ad198eb7 <unknown>
#19 0x5611ad16710f <unknown>
#20 0x5611ad1b6828 <unknown>
#21 0x5611ad1b69f0 <unknown>
#22 0x5611ad1c6f86 <unknown>
#23 0x7f63cf90e144 <unknown>
; 23483)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 274, in selenium_scraper
    driver.get("https://www.google.com")
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.353
  (Session info: chrome=130.0.6723.58)
Stacktrace:
#0 0x5611ad1c810a <unknown>
#1 0x5611acce3460 <unknown>
#2 0x5611acccbb00 <unknown>
#3 0x5611acccb7ed <unknown>
#4 0x5611accc987c <unknown>
#5 0x5611accca02f <unknown>
#6 0x5611accd9497 <unknown>
#7 0x5611accef474 <unknown>
#8 0x5611accf47ab <unknown>
#9 0x5611accca73e <unknown>
#10 0x5611accef2d8 <unknown>
#11 0x5611acd72d5b <unknown>
#12 0x5611acd53db3 <unknown>
#13 0x5611acd22c10 <unknown>
#14 0x5611acd23bee <unknown>
#15 0x5611ad19439b <unknown>
#16 0x5611ad198338 <unknown>
#17 0x5611ad181ebc <unknown>
#18 0x5611ad198eb7 <unknown>
#19 0x5611ad16710f <unknown>
#20 0x5611ad1b6828 <unknown>
#21 0x5611ad1b69f0 <unknown>
#22 0x5611ad1c6f86 <unknown>
#23 0x7f63cf90e144 <unknown>

[2024-10-23T08:36:02.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T08:36:02.440+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T08:36:02.441+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
