[2024-10-25T00:00:06.275+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-25T00:00:06.293+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: frank_dag.start_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T00:00:06.301+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: frank_dag.start_task scheduled__2024-10-24T00:00:00+00:00 [queued]>
[2024-10-25T00:00:06.302+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-25T00:00:06.321+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): start_task> on 2024-10-24 00:00:00+00:00
[2024-10-25T00:00:06.327+0000] {standard_task_runner.py:72} INFO - Started process 29173 to run task
[2024-10-25T00:00:06.332+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'frank_dag', 'start_task', 'scheduled__2024-10-24T00:00:00+00:00', '--job-id', '950', '--raw', '--subdir', 'DAGS_FOLDER/frank_dag.py', '--cfg-path', '/tmp/tmpiktrrtwf']
[2024-10-25T00:00:06.336+0000] {standard_task_runner.py:105} INFO - Job 950: Subtask start_task
[2024-10-25T00:00:06.390+0000] {task_command.py:467} INFO - Running <TaskInstance: frank_dag.start_task scheduled__2024-10-24T00:00:00+00:00 [running]> on host 60bbe790d101
[2024-10-25T00:00:06.487+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='frank_dag' AIRFLOW_CTX_TASK_ID='start_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-24T00:00:00+00:00'
[2024-10-25T00:00:06.488+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-25T00:00:06.516+0000] {baseoperator.py:405} WARNING - SlackWebhookOperator.execute cannot be called outside TaskInstance!
[2024-10-25T00:00:06.523+0000] {base.py:84} INFO - Retrieving connection 'slack_webhook'
[2024-10-25T00:00:06.882+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-25T00:00:06.890+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-25T00:00:06.891+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=frank_dag, task_id=start_task, run_id=scheduled__2024-10-24T00:00:00+00:00, execution_date=20241024T000000, start_date=20241025T000006, end_date=20241025T000006
[2024-10-25T00:00:06.891+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_success_callback
[2024-10-25T00:00:06.892+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: slack_success_callback
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/frank_dag.py", line 47, in slack_success_callback
    return send_slack_message(context, ":large_green_circle: Task Succeeded.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/frank_dag.py", line 28, in send_slack_message
    slack_notification = SlackWebhookOperator(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 87, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 956, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 250, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'slack_notification_20241025_000006' has already been added to the DAG
[2024-10-25T00:00:06.950+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-25T00:00:06.974+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-25T00:00:06.979+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
