[2024-10-24T10:49:29.601+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-24T10:49:29.614+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:45:41.452218+00:00 [queued]>
[2024-10-24T10:49:29.622+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:45:41.452218+00:00 [queued]>
[2024-10-24T10:49:29.622+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-24T10:49:29.642+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-24 10:45:41.452218+00:00
[2024-10-24T10:49:29.649+0000] {standard_task_runner.py:72} INFO - Started process 10640 to run task
[2024-10-24T10:49:29.653+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test3', 'run_selenium_task', 'manual__2024-10-24T10:45:41.452218+00:00', '--job-id', '912', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpsra6btn7']
[2024-10-24T10:49:29.655+0000] {standard_task_runner.py:105} INFO - Job 912: Subtask run_selenium_task
[2024-10-24T10:49:29.702+0000] {task_command.py:467} INFO - Running <TaskInstance: test3.run_selenium_task manual__2024-10-24T10:45:41.452218+00:00 [running]> on host 60bbe790d101
[2024-10-24T10:49:29.795+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test3' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T10:45:41.452218+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T10:45:41.452218+00:00'
[2024-10-24T10:49:29.796+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-24T10:49:29.821+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:49:29.944+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:49:30.127+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:49:30.246+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:49:52.350+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:49:52.470+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:49:52.589+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:49:52.712+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:50:14.703+0000] {logging_mixin.py:190} INFO - 現在產線又是一波大徵才了吧
[2024-10-24T10:50:14.782+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 98, in selenium_scraper
    time = driver1.find_element(By.TAG_NAME, "time").get_attribute('datetime')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"time"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5582691f010a <unknown>
#1 0x558268d0b460 <unknown>
#2 0x558268d57f96 <unknown>
#3 0x558268d58221 <unknown>
#4 0x558268d9d5d4 <unknown>
#5 0x558268d7c03d <unknown>
#6 0x558268d9aaf6 <unknown>
#7 0x558268d7bdb3 <unknown>
#8 0x558268d4ac10 <unknown>
#9 0x558268d4bbee <unknown>
#10 0x5582691bc39b <unknown>
#11 0x5582691c0338 <unknown>
#12 0x5582691a9ebc <unknown>
#13 0x5582691c0eb7 <unknown>
#14 0x55826918f10f <unknown>
#15 0x5582691de828 <unknown>
#16 0x5582691de9f0 <unknown>
#17 0x5582691eef86 <unknown>
#18 0x7f2f2ee2b144 <unknown>

[2024-10-24T10:50:14.790+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test3, task_id=run_selenium_task, run_id=manual__2024-10-24T10:45:41.452218+00:00, execution_date=20241024T104541, start_date=20241024T104929, end_date=20241024T105014
[2024-10-24T10:50:14.803+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-24T10:50:14.804+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 912 for task run_selenium_task (Message: no such element: Unable to locate element: {"method":"tag name","selector":"time"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5582691f010a <unknown>
#1 0x558268d0b460 <unknown>
#2 0x558268d57f96 <unknown>
#3 0x558268d58221 <unknown>
#4 0x558268d9d5d4 <unknown>
#5 0x558268d7c03d <unknown>
#6 0x558268d9aaf6 <unknown>
#7 0x558268d7bdb3 <unknown>
#8 0x558268d4ac10 <unknown>
#9 0x558268d4bbee <unknown>
#10 0x5582691bc39b <unknown>
#11 0x5582691c0338 <unknown>
#12 0x5582691a9ebc <unknown>
#13 0x5582691c0eb7 <unknown>
#14 0x55826918f10f <unknown>
#15 0x5582691de828 <unknown>
#16 0x5582691de9f0 <unknown>
#17 0x5582691eef86 <unknown>
#18 0x7f2f2ee2b144 <unknown>
; 10640)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 98, in selenium_scraper
    time = driver1.find_element(By.TAG_NAME, "time").get_attribute('datetime')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"tag name","selector":"time"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x5582691f010a <unknown>
#1 0x558268d0b460 <unknown>
#2 0x558268d57f96 <unknown>
#3 0x558268d58221 <unknown>
#4 0x558268d9d5d4 <unknown>
#5 0x558268d7c03d <unknown>
#6 0x558268d9aaf6 <unknown>
#7 0x558268d7bdb3 <unknown>
#8 0x558268d4ac10 <unknown>
#9 0x558268d4bbee <unknown>
#10 0x5582691bc39b <unknown>
#11 0x5582691c0338 <unknown>
#12 0x5582691a9ebc <unknown>
#13 0x5582691c0eb7 <unknown>
#14 0x55826918f10f <unknown>
#15 0x5582691de828 <unknown>
#16 0x5582691de9f0 <unknown>
#17 0x5582691eef86 <unknown>
#18 0x7f2f2ee2b144 <unknown>

[2024-10-24T10:50:14.819+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-24T10:50:14.833+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T10:50:14.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
