[2024-10-24T10:22:29.292+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-24T10:22:29.317+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:01:22.781255+00:00 [queued]>
[2024-10-24T10:22:29.331+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:01:22.781255+00:00 [queued]>
[2024-10-24T10:22:29.331+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-24T10:22:29.358+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-24 10:01:22.781255+00:00
[2024-10-24T10:22:29.364+0000] {standard_task_runner.py:72} INFO - Started process 9449 to run task
[2024-10-24T10:22:29.368+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test3', 'run_selenium_task', 'manual__2024-10-24T10:01:22.781255+00:00', '--job-id', '905', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmperxjv422']
[2024-10-24T10:22:29.370+0000] {standard_task_runner.py:105} INFO - Job 905: Subtask run_selenium_task
[2024-10-24T10:22:29.419+0000] {task_command.py:467} INFO - Running <TaskInstance: test3.run_selenium_task manual__2024-10-24T10:01:22.781255+00:00 [running]> on host 60bbe790d101
[2024-10-24T10:22:29.508+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test3' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T10:01:22.781255+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T10:01:22.781255+00:00'
[2024-10-24T10:22:29.509+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-24T10:22:29.532+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:22:29.652+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:22:29.779+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:22:29.953+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:22:52.229+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:22:52.346+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:22:52.465+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:22:52.590+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:23:04.482+0000] {logging_mixin.py:190} INFO - 現在產線又是一波大徵才了吧 - 科技業板 | Dcard
[2024-10-24T10:23:14.817+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 221, in selenium_scraper
    print(data1)
          ^^^^^
UnboundLocalError: cannot access local variable 'data1' where it is not associated with a value
[2024-10-24T10:23:14.825+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test3, task_id=run_selenium_task, run_id=manual__2024-10-24T10:01:22.781255+00:00, execution_date=20241024T100122, start_date=20241024T102229, end_date=20241024T102314
[2024-10-24T10:23:14.840+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-24T10:23:14.841+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 905 for task run_selenium_task (cannot access local variable 'data1' where it is not associated with a value; 9449)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 221, in selenium_scraper
    print(data1)
          ^^^^^
UnboundLocalError: cannot access local variable 'data1' where it is not associated with a value
[2024-10-24T10:23:14.892+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-24T10:23:14.905+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T10:23:14.906+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
